# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

# Nom du workflow, ici j'ai mis le nom en fonction de ce qu'on a au labo à la question3
name: Construire le conteneur et le publier sur le registre GitHub Packages

# Déclencheur du workflow
on:
  push:
    branches:
      - main # Dès qu'on push sur le main

jobs:
  build:
    # Environnement d'exécution : machine virtuelle Linux
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupère le code source du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configure Docker Buildx pour des fonctionnalités avancées de build
      - name: Configurer Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Étape 3 : Se connecter au GitHub Docker Registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 4 : Construire le conteneur et le publier sur le registre GitHub Packages
      - name: Construire le conteneur et le publier sur le registre GitHub Packages
        uses: docker/build-push-action@v5
        with:
          context: . # Utilise le répertoire courant pour construire l'image
          push: true
          tags: ghcr.io/shirozztm/ue19-lab-05/my-app:latest # identifiant de l'image Docker taguée
