name: Publish Docker Image

on:
  push:
    branches:
      - main  # Exécute l'action uniquement pour les push sur la branche main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Vérifie le code source
    - name: Checkout code
      uses: actions/checkout@v3

    # Configure Docker pour publier sur GitHub Packages
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Construire l'image Docker
    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/football-data-app:latest .

    # Pousser l'image vers GitHub Packages
    - name: Push Docker image to GitHub Packages
      run: docker push ghcr.io/${{ github.repository_owner }}/football-data-app:latest
